#!/bin/bash
# Fungsi untuk membuat "kelas" Person
#
# Mohon gunakan mush 
#if [[ "${BASH_SOURCE[0]}" != "${0}" ]]; then
  #  echo -e "warn: Wrong move, you should type \`bash ${BASH_SOURCE[0]}' not \`source ${BASH_SOURCE[@]}'." 1>&2
#    return 1
#fi

#if [[ ! $- =~ i ]]; then 
#  echo -e "warn: Wrong move, you should type \`bash ${0}' not \`source ${0}'." 1>&2;
#  exit 1; 
#:fi
Person() {
    local self=$1
    declare -gA "${self}"

    # Inisialisasi properti
    eval "${self}['name']=''"
    eval "${self}['username']=''"
    eval "${self}['age']=''"
    eval "${self}['hobbies']=''"
    eval "${self}['job']=''"

    # Metode untuk mengatur nama
    eval "
        function ${self}.setName {
            local name=\$1
            ${self}['name']=\$name
          }
    "

    # Metode untuk mengatur usia
    eval "
        function ${self}.setAge {
            local age=\$1
            ${self}['age']=\$age
        }
    "

    # Metode untuk mengatur username
    eval "
        function ${self}.setUsername {
            local username=\$1
            ${self}['username']=\$username
        }
    "

    # Metode untuk mengatur pekerjaan
    eval "
        function ${self}.setJob {
            local job=\$1
            ${self}['job']=\$job
        }
    "

    # Metode untuk mengatur hobi
    eval "
        function ${self}.setHobbies {
            local hobbies=\$@
            ${self}['hobbies']=\$hobbies
        }
    "

    # Metode untuk mendapatkan informasi
    eval "
        function ${self}.getInfo { 
        echo -e \"{'Name': \${${self}['name']}, 'Username': \${${self}['username']}, 'Age': \${${self}['age']}, 'Hobbies': \${${self}['hobbies']}, 'Job': \${${self}['job']}}\"
        }
    " 
}

# Contoh penggunaan kelas Person
function main()
{
declare -A {{name}}
Person {{name}}
read -a hobbies < <(echo [ \"$HOBI1\", \"$HOBI2\", \"$HOBI3\" ])
{{name}}.setName "\"$NAME\""
{{name}}.setAge "\"$AGE\""
{{name}}.setUsername "\"$USERNAME\""
{{name}}.setHobbies "${hobbies[@]}"
{{name}}.setJob "\"$JOB\""

mkdir -p $HOME/dataset/biodata/{{name}}
touch $HOME/dataset/biodata/{{name}}/person.profile

if ! grep -q 'source $HOME/dataset/biodata/{{name}}/person.profile' ~/.bashrc; then

cat >> ~/.bashrc <<EOF

# LOAD ENV VARIABLE FOR PERSON.sh generated by automaticaly system
source $HOME/dataset/biodata/{{name}}/person.profile
EOF
fi
# Menampilkan informasi

{{name}}.getInfo | sed "s/'/\"/g" | jq .
  return 0
}


if $(cat ${0} | grep -q "{{name}}"); then
  echo -e "info: Please set up variable first with mushtache!\n"
  exit 2
else
  main
fi
